### ISSUE TITLE
[AVM Module Issue]:  "The policy set 'Enforce-Encryption-CMK' could not be parameterized because the default value of a policy set parameter referenced by policy definition 76a56461-9dc0-40f0-82f5-2453283afa2f was not valid for that policy definition.

### ISSUE THREAD

**Issue by olibbb** [Azure/terraform-azurerm-avm-ptn-alz#182]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.11.0

### Description

Deploying example with private dns zones results in error during apply : 
 {
│   "error": {
│     "code": "InvalidPolicyParameters",
│     "message": "The policy set 'Enforce-Encryption-CMK' could not be parameterized because the default value of a policy set parameter referenced by policy definition 76a56461-9dc0-40f0-82f5-2453283afa2f was not valid for that policy definition. Please verify that the default values of all policy set parameters are valid in the context of the policy definitions referencing them. The inner exception 'The value 'Deny' is not allowed for policy parameter 'effect' in policy definition '76a56461-9dc0-40f0-82f5-2453283afa2f'. The allowed values are 'AuditIfNotExists, Disabled'.'."
│   }
│ }

I tried :

    alzroot = {
      policy_assignments = {
        # Modify the encryption policy to be disabled due to default parameter being incorrect.
        Enforce-Encryption-CMK = {
          parameters = {
            effect = jsonencode({ value = "Disabled" })
          }
        }
      }
    }

But then it complains that the policy assignment does not exist therefor I can't modify the assignment in this way.

Can you please advise? :)

**Comment by OskarKlintrot** [comment]
You can create `lib\policy_set_definitions\policy_set_definition_es_enforce_encryption_cmk.alz_policy_set_definition.json` and copy the content from [Enforce-Encryption-CMK.json](https://raw.githubusercontent.com/Azure/Enterprise-Scale/refs/heads/main/src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK.json) to the file you just created and make the necessary changes. Unfortunately, I don't know what they are... I just change the default value it's complaining about but that gave me this error instead:

```log
module.management_groups.module.management_groups.azapi_resource.policy_set_definitions["xxx/Enforce-Encryption-CMK"]: Creating...
╷
│ Error: Failed to create/update resource
│ 
│   with module.management_groups.module.management_groups.azapi_resource.policy_set_definitions["xxx/Enforce-Encryption-CMK"],
│   on .terraform/modules/management_groups.management_groups/main.policy_set_definitions.tf line 1, in resource "azapi_resource" "policy_set_definitions":
│    1: resource "azapi_resource" "policy_set_definitions" {
│ 
│ creating/updating Resource: (ResourceId
│ "/providers/Microsoft.Management/managementGroups/xxx/providers/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK"
│ / Api Version "2023-04-01"): PUT
│ https://management.azure.com/providers/Microsoft.Management/managementGroups/xxx/providers/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: UnusedPolicyParameters
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "UnusedPolicyParameters",
│     "message": "The policy set '<null>' has defined parameters 'ACRCmkEffect,AksCmkEffect,AutomationAccountCmkEffect,AzureBatchCMKEffect,BackupCmkEffect,CognitiveServicesCMKEffect,CosmosCMKEffect,DataBoxCMKEffect,EncryptedVMDisksEffect,HealthcareAPIsCMKEffect,MySQLCMKEffect,PostgreSQLCMKEffect,SqlServerTDECMKEffect,StorageCMKEffect,StreamAnalyticsCMKEffect,SynapseWorkspaceCMKEffect,WorkspaceCMKEffect,adfCmk,adxCmk,botServiceCmk,cognitiveSearchCmk,containerInstanceCmk,eventHubNamespacesCmk,eventHubPremiumCmk,osAndDataDiskCmk,serviceBusDenyCmk,sqlManagedCmk,storageAccountsEncryptionCmk,storageQueueCmk,storageTableCmk' which are not used in referenced policy definitions. Please either remove these parameters from the definition or ensure that they are used."
│   }
│ }
│ --------------------------------------------------------------------------------

```

**Comment by abelal83** [comment]
Also seeing the same issue deploying to a new tenant

```
│ Error: Failed to create/update resource
│ 
│   with module.core_alz_accelerator.module.management_groups.module.management_groups.azapi_resource.policy_set_definitions["ckn-root-grp/Enforce-Encryption-CMK"],
│   on .terraform/modules/core_alz_accelerator.management_groups.management_groups/main.policy_set_definitions.tf line 1, in resource "azapi_resource" "policy_set_definitions":
│    1: resource "azapi_resource" "policy_set_definitions" {
│ 
│ creating/updating Resource: (ResourceId
│ "/providers/Microsoft.Management/managementGroups/ckn-root-grp/providers/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK"
│ / Api Version "2023-04-01"): PUT
│ https://management.azure.com/providers/Microsoft.Management/managementGroups/ckn-root-grp/providers/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidPolicyParameters
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidPolicyParameters",
│     "message": "The policy set 'Enforce-Encryption-CMK' could not be parameterized because the default value of a policy set parameter referenced by policy definition 76a56461-9dc0-40f0-82f5-2453283afa2f was not valid for that policy definition. Please verify that the default values of all policy set parameters are valid in the context of the policy definitions referencing them. The inner exception 'The value 'Deny' is not allowed for policy parameter 'effect' in policy definition '76a56461-9dc0-40f0-82f5-2453283afa2f'. The allowed values are 'AuditIfNotExists, Disabled'.'."
│   }
│ }
│ --------------------------------------------------------------------------------

```

I've deployed this successfully to another tenant with no issues. What has changed?

**Comment by olibbb** [comment]
@OskarKlintrot How are you doing this exactly? I added the lib folder and lib reference. Added the json in the path you specified but then I get the error : 

│ Error: Failed to initialize AlzLib
│ 
│   with provider["registry.terraform.io/azure/alz"],
│   on main.tf line 1, in provider "alz":
│    1: provider "alz" {
│ 
│ Alzlib.Init: error adding processed result to AlzLib:
│ Alzlib.addProcessedResult: policy definition Enforce-Encryption-CMK already
│ exists in the library


Thanks :)

**Comment by abelal83** [comment]
@olibbb you've tried this which will disable assignment
```
alzroot = {
  policy_assignments = {
    # Modify the encryption policy to be disabled due to default parameter being incorrect.
    Enforce-Encryption-CMK = {
      parameters = {
        effect = jsonencode({ value = "Disabled" })
      }
    }
  }
}
```

Is there a way to disable the policy definition completely until there's a solution to this problem?

**Comment by olibbb** [comment]
Alright, I updated the platform/alz lib to the latest version found here : https://azure.github.io/Azure-Landing-Zones/terraform/howtos/update/ and I don't seem to get this error anymore but I'm dealing with a whole slew of auth errors and other errors now. I think the recommended way is to use the accelerator deployment so I'm gonna try that instead of calling this module example directly.

**Comment by matt-FFFFFF** [comment]
Hi!

Yes we updated the library today because of an upstream change in a built in policy.

Using the Feb 2025 release should solve the issue.

If you have already deployed the accelerator, then just change your local library metadata file to reference the new release and it should all work. You shouldn't need to run the accelerator again.

#RR

/cc @jaredfholgate

**Comment by OskarKlintrot** [comment]
@matt-FFFFFF I updated the alz version and set lib ref but it still doesn't work for me. The following:

```hcl
terraform {
  required_version = "~> 1.9"
  required_providers {
    alz = {
      source  = "Azure/alz"
~     version = "~> 0.17"
    }
    [...]
  }
  backend "azurerm" {}
}

provider "alz" {
  library_overwrite_enabled = true
  library_references = [
+   {
+     path = "platform/alz"
+     ref  = "2025.02.0"
+   },
    {
      custom_url = "${path.root}/lib"
    }
  ]
}
```

gives me:

![Image](https://github.com/user-attachments/assets/9bb5dcdd-f21e-4fa7-a4b8-0199b92b6f6d)

Is there anything more to do than run `terraform init -upgrade`?

**Comment by matt-FFFFFF** [comment]
Did you use the accelerator?

If so there's a metadata file in your custom lib. You need to change the dependency in there.

#RR

**Comment by abelal83** [comment]
@matt-FFFFFF that worked me by updating the metadata file.

**Comment by OskarKlintrot** [comment]
@matt-FFFFFF Same for me, classic PEBKAC!
